### ISSUE TITLE
Folder .idea

### ISSUE THREAD

**Issue by Vieja** [Vieja/Catan-Image-Recognition#3]
Czy on jest potrzebny żeby go pushowac? Bo widzę że jest w .gitignore ale nadal git mi śledzi zmiany w nim. #2

**Comment by PiotrJTomaszewski** [comment]
Tam jest tylko jakaś konfiguracja PyCharma i raczej nie będzie nam potrzebny

**Comment by PiotrJTomaszewski** [comment]
Wygląda na to, że z jakiegoś powodu samo wykluczenie .idea nie wystarcza. Jakby co, działający gitignore do pycharma możesz sobie wygenerować na http://gitignore.io

**Comment by Vieja** [comment]
git rm --cached -r .idea załatwiło sprawę

**Comment by Vieja** [comment]
Dzięki za link, przyda się w przyszłości
